// apps/dashboard-qwik/src/components/dashboard/header.tsx
import { component$ } from "@builder.io/qwik";

export default component$<{
    value: {
        user: {
            username: string;
            email: string;
        };
        userWorkspaces: ({
            id: string;
            name: string;
            slug: string;
            image: string | null;
        } | null)[];
        currentWorkspace: {
            id: string;
            name: string;
        };
    }
}>(({ value: { currentWorkspace } }) => {
    return <header class="flex w-full items-center justify-between">
        <div class="flex flex-row items-center space-x-3">
            <p>{currentWorkspace.name}</p>
        </div>
    </header>
});

// apps/newsletter/src/components/header.tsx
import Link from "next/link";

export default function Header() {
    return (
        <div className="flex justify-between h-12 items-center">
            <h2>Newsletter</h2>
            <div className="flex space-x-2">
                <Link href="/create">Create</Link>
                <Link href="/about">About</Link>
                <Link href="/pricing">Pricing</Link>
            </div>
        </div>
    )
}
