// apps/dashboard-qwik/src/components/ui/Textarea/index.tsx
import { component$, type QwikIntrinsicElements } from '@builder.io/qwik';

export interface TextareaProps extends Omit<QwikIntrinsicElements['textarea'], 'class'> {
    class?: string;
}

export const Textarea = component$<TextareaProps>((props) => {
    const { class: className = '', ...restProps } = props;

    return (
        <textarea
            class={`flex min-h-[80px] w-full resize-none rounded-md border border-neutral-100 bg-neutral-100 px-3 py-2 text-sm outline-none ring-offset-background transition-all placeholder:text-muted-foreground hover:bg-neutral-200 focus-visible:bg-neutral-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-300 disabled:cursor-not-allowed disabled:opacity-50 ${className}`}
            {...restProps}
        />
    );
});

// packages/ui/src/components/textarea.tsx
import type { ComponentProps } from "react";
import { cn } from "../lib/cn";

type TextareaProps = ComponentProps<"textarea">;

function Textarea({ className, ...props }: TextareaProps) {
  return (
    <textarea
      className={cn(
        "flex min-h-24 w-full rounded-3xl border-2 border-neutral-200 bg-background px-6 py-4 text-base text-foreground outline-none transition-colors placeholder:text-muted-foreground focus-visible:border-neutral-400 focus-visible:ring-2 focus-visible:ring-neutral-200 disabled:cursor-not-allowed disabled:opacity-50 aria-invalid:border-destructive aria-invalid:ring-2 aria-invalid:ring-destructive/20 dark:border-neutral-700 dark:bg-neutral-900 dark:focus-visible:border-neutral-500 dark:focus-visible:ring-neutral-700",
        className
      )}
      {...props}
    />
  );
}

export { Textarea };
