// apps/dashboard-qwik/src/components/dashboard/header.tsx
import { component$ } from "@builder.io/qwik";

export default component$<{
    value: {
        user: {
            username: string;
            email: string;
        };
        userWorkspaces: ({
            id: string;
            name: string;
            slug: string;
            image: string | null;
        } | null)[];
        currentWorkspace: {
            id: string;
            name: string;
            image: string | null;
        };
    };
}>(({ value: { currentWorkspace } }) => {
    return (
        <header class="flex w-full items-center justify-between">
            <div class="flex cursor-pointer flex-row items-center space-x-3 rounded-lg pr-1 transition hover:bg-neutral-200 hover:ring-4 hover:ring-neutral-200">
                {currentWorkspace.image ? (
                    <img
                        src={currentWorkspace.image}
                        alt={currentWorkspace.name}
                        class="h-7 w-7 rounded-lg object-cover"
                    />
                ) : (
                    <div class="flex h-7 w-7 items-center justify-center rounded-lg bg-neutral-600 font-medium text-lg text-white">
                        {currentWorkspace.name.charAt(0).toUpperCase()}
                    </div>
                )}
                <h3 class="font-medium text-lg">{currentWorkspace.name}</h3>
            </div>
        </header>
    );
});

// apps/dashboard/src/components/dashboard/header.tsx
import { SettingsIcon } from "lucide-react";

export default function DashboardHeader() {
	return (
		<header className="flex items-center justify-between px-32 py-5">
			<div className="rouded-md flex cursor-pointer flex-row items-center space-x-3 rounded-md bg-transparent ring-neutral-100 transition-all hover:bg-neutral-100 hover:ring-4">
				<img
					src="https://avatars.githubusercontent.com/u/178011817?s=200&v=4"
					alt="Selfmail Logo"
					className="h-5 w-5 rounded-md"
				/>
				<p className="font-medium">Selfmail</p>
			</div>
			<div className="flex items-center space-x-3">
				<SettingsIcon className="h-4 w-4 rounded-md bg-transparent text-neutral-700 transition-colors hover:bg-neutral-100" />
			</div>
		</header>
	);
}
