// apps/dashboard-qwik/src/components/dashboard/navigation.tsx
import { component$, useStore, useTask$ } from "@builder.io/qwik";
import { Link, server$, useLocation } from "@builder.io/qwik-city";
import { LuPlaneTakeoff } from "@qwikest/icons/lucide";
import { db } from "database";
import {
    middlewareAuthentication,
    verifyWorkspaceMembership,
} from "~/lib/auth";
import type { MemberInSharedMap } from "~/routes/workspace/[workspaceSlug]/types";
import { NavLink } from "../ui/NavLink";

const getAddresses = server$(async function () {
    const sessionToken = this.cookie.get("selfmail-session-token")?.value;
    const workspaceSlug = this.params.workspaceSlug;

    if (!workspaceSlug || !sessionToken) {
        throw Error("No workspace slug or session token provided.");
    }

    const { authenticated, user } = await middlewareAuthentication(sessionToken);

    if (!authenticated || !user) {
        throw Error("User is not authenticated. Please log in.");
    }

    const { isMember, member, workspace } = await verifyWorkspaceMembership(
        user.id,
        workspaceSlug,
    );

    if (!isMember || !member || !workspace) {
        throw Error("User is not a member of this workspace. Access denied.");
    }
    const memberAddresses = await db.address.findMany({
        where: {
            MemberAddress: {
                every: {
                    memberId: member.id,
                },
            },
        },
    });

    return memberAddresses;
});

export default component$(() => {
    const location = useLocation();
    const addresses = useStore({
        data: [] as { id: string; email: string }[],
    });

    useTask$(async ({ track }) => {
        track(() => location.params.workspaceSlug);
        addresses.data = await getAddresses();
    });

    const links = {
        platform: {
            api: "/api",
            ai: "/ai",
            workflows: "/workflows",
        },
        workspace: {
            member: "/members",
            billing: "/billing",
            settings: "/settings",
        },
    };

    return (
        <div class="flex w-full flex-row justify-between">
            <div class="flex flex-col gap-3">
                <p class="text-neutral-700 text-sm">Addresses</p>
                <NavLink
                    groupHover={false}
                    href={`/workspace/${location.params.workspaceSlug}/compose${location.params.addressId ? `?addressId=${location.params.addressId}` : ""}`}
                    class="flex w-min items-center space-x-3 rounded-xl border border-neutral-300 border-dashed p-2 text-center text-neutral-600 text-sm hover:bg-neutral-100! hover:ring-0!"
                    prefetch
                >
                    <LuPlaneTakeoff class="inline-block h-5 w-5" />
                    <span>Compose</span>
                </NavLink>
                {addresses.data.map((address) => (
                    <NavLink
                        key={address.id}
                        href={`/workspace/${location.params.workspaceSlug}/address/${address.id}`}
                        activeClass="bg-blue-100 text-blue-700 font-medium"
                    >
                        {address.email}
                    </NavLink>
                ))}

                {(addresses.data.length === 0 && (
                    <p class="text-neutral-500 text-sm">
                        No addresses found. Create a{" "}
                        <Link
                            href={`/workspace/${location.params.workspaceSlug}/address/new`}
                            class="text-blue-500"
                            prefetch
                        >
                            new address
                        </Link>
                        .
                    </p>
                )) || (
                        <Link
                            href={`/workspace/${location.params.workspaceSlug}/address/new`}
                            class="text-blue-500 text-sm"
                            prefetch
                        >
                            + Add new address
                        </Link>
                    )}
            </div>
            <div class="flex flex-col gap-3">
                <p class="text-neutral-700 text-sm">Platform</p>
                {links.platform &&
                    Object.entries(links.platform).map(([key, value]) => (
                        <NavLink
                            key={key}
                            href={`/workspace/${location.params.workspaceSlug}${value}`}
                            activeClass="bg-blue-100 text-blue-700 font-medium"
                        >
                            {key.charAt(0).toUpperCase() + key.slice(1)}
                        </NavLink>
                    ))}
            </div>
            <div class="flex flex-col gap-3">
                <p class="text-neutral-700 text-sm">Workspace</p>
                {links.workspace &&
                    Object.entries(links.workspace).map(([key, value]) => (
                        <NavLink
                            key={key}
                            href={`/workspace/${location.params.workspaceSlug}${value}`}
                            activeClass="bg-blue-100 text-blue-700 font-medium"
                        >
                            {key.charAt(0).toUpperCase() + key.slice(1)}
                        </NavLink>
                    ))}
            </div>
        </div>
    );
});

// apps/dashboard/src/components/dashboard/navigation.tsx
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { toast } from "sonner";
import { client } from "@/lib/client";
import { NavLink } from "./nav-link";

export default function DashboardNavigation({
	workspaceId,
}: {
	workspaceId: string;
}) {
	const { data, error, isFetching } = useQuery({
		queryKey: ["addresses", workspaceId],
		queryFn: async () => {
			const addresses = await client.v1.web.dashboard.addresses.get({
				query: {
					workspaceId,
				},
			});

			if (addresses.error) {
				console.log("API Error:", addresses.error);
				throw new Error("Internal Server Error. Please try again later!");
			}
			return addresses.data;
		},
	});

	if (error && !isFetching) {
		toast.error("Failed to load addresses. Please try again later.");
		console.log(error);
		return (
			<div className="flex w-full flex-row items-start justify-between px-4 py-5 sm:px-6 lg:px-26 xl:px-32">
				<div className="text-red-500">Failed to load navigation data.</div>
			</div>
		);
	}

	if (isFetching) {
		return (
			<div className="flex w-full flex-row items-start justify-between px-4 py-5 sm:px-6 lg:px-26 xl:px-32">
				<div className="text-gray-500">Loading navigation...</div>
			</div>
		);
	}

	return (
		<div className="flex w-full flex-row items-start justify-between px-4 py-5 sm:px-6 lg:px-26 xl:px-32">
			<div className="flex flex-col space-y-2">
				<p className="font-medium">Mail</p>
				<NavLink href={`/workspace/${workspaceId}/compose`}>
					Compose Email
				</NavLink>
				{data?.map((address) => (
					<NavLink
						key={address.id}
						href={`/workspace/${workspaceId}/address/${address.id}`}
					>
						{address.email}
					</NavLink>
				))}
				{data?.length === 0 && (
					<p className="text-gray-500 text-sm">
						No addresses found.{" "}
						<Link
							to="/workspace/$workspaceId/address/create"
							params={{ workspaceId }}
							className="underline"
						>
							Create a new one.
						</Link>
					</p>
				)}
				{data && data.length < 0 && (
					<div className="flex w-min flex-row items-center space-x-0.5 rounded-md bg-transparent p-2 ring-neutral-100 transition-all hover:bg-neutral-100 hover:ring-4">
						<span className="h-1 w-1 rounded-full bg-neutral-600" />
						<span className="h-1 w-1 rounded-full bg-neutral-600" />
						<span className="h-1 w-1 rounded-full bg-neutral-600" />
					</div>
				)}
			</div>
			<div className="flex flex-col space-y-2">
				<p className="font-medium">Workspace</p>
				<NavLink href="/workflows">Workflows</NavLink>
				<NavLink href="/members">Members</NavLink>
			</div>
			<div className="flex flex-col space-y-2">
				<p className="font-medium">Settings</p>
				<NavLink href="/settings/workspace">Workspace Settings</NavLink>
				<NavLink href="/settings/profile">Profile Settings</NavLink>
				<NavLink href="/settings/user">User Settings</NavLink>
				<div className="flex w-min flex-row items-center space-x-0.5 rounded-md bg-transparent p-2 ring-neutral-100 transition-all hover:bg-neutral-100 hover:ring-4">
					<span className="h-1 w-1 rounded-full bg-neutral-600" />
					<span className="h-1 w-1 rounded-full bg-neutral-600" />
					<span className="h-1 w-1 rounded-full bg-neutral-600" />
				</div>
			</div>
		</div>
	);
}
