// apps/dashboard-qwik/src/components/dashboard/header.tsx
import { component$ } from "@builder.io/qwik";

export default component$<{
    value: {
        user: {
            username: string;
            email: string;
        };
        userWorkspaces: ({
            id: string;
            name: string;
            slug: string;
            image: string | null;
        } | null)[];
        currentWorkspace: {
            id: string;
            name: string;
            image: string | null;
        };
    };
}>(({ value: { currentWorkspace } }) => {
    return (
        <header class="flex w-full items-center justify-between">
            <div class="flex cursor-pointer flex-row items-center space-x-3 rounded-lg pr-1 transition hover:bg-neutral-200 hover:ring-4 hover:ring-neutral-200">
                {currentWorkspace.image ? (
                    <img
                        src={currentWorkspace.image}
                        alt={currentWorkspace.name}
                        class="h-7 w-7 rounded-lg object-cover"
                    />
                ) : (
                    <div class="flex h-7 w-7 items-center justify-center rounded-lg bg-neutral-600 font-medium text-lg text-white">
                        {currentWorkspace.name.charAt(0).toUpperCase()}
                    </div>
                )}
                <h3 class="font-medium text-lg">{currentWorkspace.name}</h3>
            </div>
        </header>
    );
});

// apps/web/src/components/elements/header.tsx
"use client"

import Link from "next/link"
import BoxLight from "@/../public/box-light.svg"
import BoxDark from "@/../public/box.svg"
import { useTheme } from "next-themes"
import Img from "next/image"
export default function Header() {
    const theme = useTheme()
    return (
        <div className="w-full h-14 flex items-center justify-between">
            <h2 className="text-xl font-medium flex">
                {theme.theme === "dark"? <Img className="mr-2" height={25} width={25} alt="out light logo" src={BoxLight} />: <Img className="mr-2" height={25} width={25} alt="our dark logo" src={BoxDark} />}
                selfmail</h2>
            <nav className="space-x-2">
                <Link className="text-[#282828] hover:text-[#111011] dark:text-[#e1e1e1] hover:dark:text-[#f5f5f5] transition" href={"/pricing"}>
                    Pricing
                </Link>
                <Link className="text-[#282828] hover:text-[#111011] dark:text-[#e1e1e1] hover:dark:text-[#f5f5f5] transition" href={"/selfhost"}>
                    Selfhost
                </Link>
                <Link className="text-[#282828] hover:text-[#111011] dark:text-[#e1e1e1] hover:dark:text-[#f5f5f5] transition" href={"/login"}>
                    Login
                </Link>
                <Link className="text-[#282828] hover:text-[#111011] dark:text-[#e1e1e1] hover:dark:text-[#f5f5f5] transition" href={"/register"}>
                    Register
                </Link>
            </nav>
        </div>
    )
}
