// apps/web/src/routes/auth/register.tsx
import { zodResolver } from "@hookform/resolvers/zod";
import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Button } from "@/components/ui/button";
import { InputGroup, InputGroupItem } from "@/components/ui/input-group";
import { useAuth } from "@/hooks/useAuth";

export const Route = createFileRoute("/auth/register")({
	component: RouteComponent,
});
// Login form validation schema
const loginSchema = z.object({
	username: z
		.string({ message: "Username is required" })
		.min(3, "Username must be at least 3 characters"),
	password: z
		.string()
		.min(1, "Password is required")
		.min(6, "Password must be at least 6 characters"),
	email: z.string().email("Invalid email address"),
});

type LoginFormData = z.infer<typeof loginSchema>;

function RouteComponent() {
	const [confirmPassword, setConfirmPassword] = useState("");
	const [password, setPassword] = useState("");
	const {
		register,
		handleSubmit,
		formState: { errors, isSubmitting },
	} = useForm<LoginFormData>({
		resolver: zodResolver(loginSchema),
	});

	const registerUser = useAuth();

	const onSubmit = async (data: LoginFormData) => {
		setPassword(data.password);
		if (data.password !== confirmPassword) return;
		try {
			registerUser.register({
				email: data.email,
				password: data.password,
				name: data.username,
			});
		} catch (error) {
			console.error("Login failed:", error);
		}
	};

	return (
		<div className="flex h-screen items-center justify-center bg-neutral-100">
			<div className="flex flex-col gap-2 lg:w-[400px]">
				<form onSubmit={handleSubmit(onSubmit)}>
					<h2 className="mb-4 font-medium text-2xl">Register</h2>
					<InputGroup className="">
						<InputGroupItem
							type="text"
							placeholder="Username"
							place="top"
							{...register("username")}
							aria-invalid={errors.username ? "true" : "false"}
						/>
						<InputGroupItem
							type="email"
							placeholder="Email"
							place="middle"
							{...register("email")}
							aria-invalid={errors.email ? "true" : "false"}
						/>
						<InputGroupItem
							type="password"
							placeholder="Password"
							place="middle"
							{...register("password")}
							aria-invalid={errors.password ? "true" : "false"}
						/>
						<InputGroupItem
							type="password"
							value={confirmPassword}
							onChange={(e) => setConfirmPassword(e.target.value)}
							placeholder="Confirm Password"
							place="bottom"
						/>
					</InputGroup>

					{/* Error messages */}
					{errors.username && (
						<p className="mt-1 text-red-600 text-sm">
							<span className="text-neutral-500">Username:</span>{" "}
							{errors.username.message}
						</p>
					)}
					{errors.email && (
						<p className="mt-1 text-red-600 text-sm">
							<span className="text-neutral-500">Email:</span>{" "}
							{errors.email.message}
						</p>
					)}
					{errors.password && (
						<p className="mt-1 text-red-600 text-sm">
							<span className="text-neutral-500">Password:</span>{" "}
							{errors.password.message}
						</p>
					)}
					{confirmPassword && password !== confirmPassword && (
						<p className="mt-1 text-red-600 text-sm">
							<span className="text-neutral-500">Confirm Password:</span>{" "}
							Passwords do not match
						</p>
					)}

					<div className="mt-4 flex w-full flex-row items-center justify-between">
						<Link to="/auth/login">
							<Button
								variant={"ghost"}
								size={"sm"}
								className="w-min text-start"
								type="button"
							>
								Login
							</Button>
						</Link>
						<Button
							size={"sm"}
							className="w-min text-end"
							type="submit"
							disabled={isSubmitting}
						>
							{isSubmitting ? "Registering..." : "Register"}
						</Button>
					</div>
				</form>
			</div>
		</div>
	);
}

// apps/dashboard-qwik/src/routes/auth/register/index.tsx
import { component$, useStore, useVisibleTask$ } from "@builder.io/qwik";
import { type DocumentHead, Form, routeAction$, z, zod$ } from "@builder.io/qwik-city";
import { LuInfo } from "@qwikest/icons/lucide";
import { db } from "database";
import { Button } from "~/components/Button";
import { Input } from "~/components/Input";
import bcrypt from "bcrypt";

export const useRegister = routeAction$(
    async ({ account: { confirmPassword, email, password, name } }) => {
        if (password !== confirmPassword) {
            return {
                fieldErrors: {
                    'account.confirmPassword': 'Passwords do not match'
                },
                failed: true
            }
        }

        const userAlreadyExists = await db.user.findUnique({
            where: {
                email
            }
        })

        if (userAlreadyExists) {
            return {
                fieldErrors: {
                    'account.email': 'A user with this email already exists'
                },
                failed: true
            }
        }

        // Hash the password with bcrypt using 12 salt rounds for security
        const saltRounds = 12;
        const hashedPassword = await bcrypt.hash(password, saltRounds);

        const user = await db.user.create({
            data: {
                email,
                name,
                password: hashedPassword
            }
        })

        if (!user) {
            return {
                fieldErrors: {
                    'account.email': 'Something went wrong, please try again later'
                },
                failed: true
            }
        }

        return {
            fieldErrors: {},
            failed: false
        }
    },
    zod$({
        account: z.object({
            name: z.string().min(2, "Name must be at least 2 characters"),
            email: z.string().email("Invalid email address"),
            password: z.string().min(8, "Password must be at least 8 characters"),
            confirmPassword: z.string().min(8, "Confirm Password must be at least 8 characters"),
        }).refine((data) => data.password === data.confirmPassword, {
            path: ["confirmPassword"],
            message: "Passwords do not match",
        })
    }))

export default component$(() => {
    const register = useRegister();

    const fieldErrors = useStore({
        name: "",
        email: "",
        password: "",
        confirmPassword: "",
    })

    useVisibleTask$(({ track }) => {
        track(() => register.value?.fieldErrors)

        if (register.value?.failed) {
            const errors = register.value.fieldErrors as Record<string, string>;
            fieldErrors.name = errors['account.name'] || ""
            fieldErrors.email = errors['account.email'] || ""
            fieldErrors.password = errors['account.password'] || ""
            fieldErrors.confirmPassword = errors['account.confirmPassword'] || ""
        } else {
            console.log("Success!")
        }
    })


    return (
        <div class="flex min-h-screen w-full items-center justify-center bg-neutral-50">
            <Form action={register} class="flex w-full max-w-md flex-col gap-4">
                <h1 class="font-medium text-2xl">Register</h1>
                <Input class="bg-neutral-200" placeholder="Name" name="account.name" required />
                {fieldErrors.name && <p class="text-red-500">{fieldErrors.name}</p>}
                <Input class="bg-neutral-200" placeholder="Email" name="account.email" type="email" required />
                {fieldErrors.email && <p class="text-red-500">{fieldErrors.email}</p>}
                <Input class="bg-neutral-200" placeholder="Password" name="account.password" type="password" required />
                {fieldErrors.password && <p class="text-red-500">{fieldErrors.password}</p>}
                <Input class="bg-neutral-200" placeholder="Confirm Password" name="account.confirmPassword" type="password" required />
                {fieldErrors.confirmPassword && <p class="text-red-500">{fieldErrors.confirmPassword}</p>}
                <Button disabled={register.isRunning}>{register.isRunning ? "Registering..." : "Register"}</Button>
                <span class="flex items-center space-x-2 text-neutral-500 text-sm">
                    <LuInfo class="inline-block h-4 w-4" />
                    <span>
                        You agree to our{" "}
                        <a href="https://selfmail.app/terms" class="underline">
                            Terms of Service
                        </a>{" "}
                        and{" "}
                        <a href="https://selfmail.app/privacy" class="underline">
                            Privacy Policy
                        </a>
                        .
                    </span>
                </span>
            </Form>
        </div>
    );
});

export const head: DocumentHead = {
    title: "Register - Selfmail",
};
