// apps/dashboard-qwik/src/components/Button/index.tsx
import { component$, type HTMLAttributes, Slot } from "@builder.io/qwik";

type ButtonProps = {} & {
  disabled?: boolean | undefined;
  formAction?: string | undefined;
  formEnctype?: string | undefined;
  formMethod?: string | undefined;
  formNoValidate?: boolean | undefined;
  formTarget?: string | undefined;
  name?: string | undefined;
  type?: "button" | "reset" | "submit" | undefined;
  popoverTargetAction?: string | undefined;
  form?: string | undefined | undefined;
  value?: string | number | readonly string[] | undefined;
  popovertarget?: string | undefined | undefined;
  popovertargetaction?: undefined;
} & HTMLAttributes<HTMLButtonElement>;

export const Button = component$<ButtonProps>((props) => {
  return (
    <button
      {...props}
      class={`inline-flex cursor-pointer items-center justify-center rounded-xl bg-neutral-800 px-4 py-1 text-lg text-white transition-colors transition-transform hover:bg-neutral-700 active:scale-97 disabled:bg-neutral-600 ${props.class ?? ""}`}
    >
      <Slot />
    </button>
  );
});

// apps/dashboard/src/components/ui/button.tsx
import type { ComponentProps } from "react";
import { cn } from "#/lib/utils";

type ButtonVariant = "default" | "outline" | "ghost" | "destructive";
type ButtonSize = "default" | "icon";

const buttonVariants = ({
	className,
	size = "default",
	variant = "default",
}: {
	className?: string;
	size?: ButtonSize;
	variant?: ButtonVariant;
} = {}) =>
	cn(
		"inline-flex cursor-pointer items-center justify-center rounded-xl font-medium outline-none transition-transform transition-colors active:scale-97 disabled:cursor-not-allowed disabled:opacity-60 disabled:active:scale-100",
		size === "default" && "px-4 py-1 text-lg",
		size === "icon" && "size-9 p-0",
		variant === "default" &&
			"bg-neutral-800 text-white hover:bg-neutral-700 disabled:bg-neutral-600",
		variant === "outline" &&
			"border border-neutral-300 bg-white text-neutral-700 hover:bg-neutral-50",
		variant === "ghost" && "text-neutral-700 hover:bg-neutral-100",
		variant === "destructive" && "bg-red-600 text-white hover:bg-red-700",
		className,
	);

type ButtonProps = ComponentProps<"button"> & {
	size?: ButtonSize;
	variant?: ButtonVariant;
};

function Button({
	className,
	size = "default",
	type = "button",
	variant = "default",
	...props
}: ButtonProps) {
	return (
		<button
			className={buttonVariants({ className, size, variant })}
			type={type}
			{...props}
		/>
	);
}

export { Button, buttonVariants };
