// packages/ui/src/components/ui/textarea.tsx
import * as React from "react";
import { cn } from "@/lib/utils";

interface TextareaProps
	extends React.TextareaHTMLAttributes<HTMLTextAreaElement> {}

const Textarea = React.forwardRef<HTMLTextAreaElement, TextareaProps>(
	({ className, ...props }, ref) => {
		return (
			<textarea
				className={cn(
					"flex min-h-[80px] w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50",
					className,
				)}
				ref={ref}
				{...props}
			/>
		);
	},
);

Textarea.displayName = "Textarea";

export { Textarea };

// apps/dashboard-qwik/src/components/ui/Textarea/index.tsx
import { component$, type QwikIntrinsicElements } from '@builder.io/qwik';

export interface TextareaProps extends Omit<QwikIntrinsicElements['textarea'], 'class'> {
    class?: string;
}

export const Textarea = component$<TextareaProps>((props) => {
    const { class: className = '', ...restProps } = props;

    return (
        <textarea
            class={`flex min-h-[80px] w-full resize-none rounded-md border border-neutral-100 bg-neutral-100 px-3 py-2 text-sm outline-none ring-offset-background transition-all placeholder:text-muted-foreground hover:bg-neutral-200 focus-visible:bg-neutral-200 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-neutral-300 disabled:cursor-not-allowed disabled:opacity-50 ${className}`}
            {...restProps}
        />
    );
});
